name: asknicely_test

volumes:
  vendor_cache: {}
  composer_cache: {}
  node_modules_cache: {}

services:
  test_db:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${DB_ADMIN_PASSWORD} || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 40

  deps:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    image: local/asknicely-test:8.2
    working_dir: /app
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    volumes:
      - ./backend:/app
      - vendor_cache:/app/vendor
      - composer_cache:/tmp/composer-cache
    command: >
      bash -lc '
        set -euo pipefail;
        composer install --no-interaction --prefer-dist
      '

  phpunit:
    image: local/asknicely-test:8.2
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    working_dir: /app
    depends_on:
      test_db:
        condition: service_healthy
      deps:
        condition: service_started
    env_file:
      - .env
    environment:
      DB_HOST: test_db
      DB_PORT: "3306"
      DB_NAME: asknicely_test
      DB_USER: asknicely_user
      DB_PASSWORD: asknicely_password
      DB_PASS: asknicely_password
    volumes:
      - ./backend:/app
      - vendor_cache:/app/vendor
    command: >
      bash -lc '
        set -euo pipefail;
        ./vendor/bin/phpunit --configuration phpunit.xml
      '

  # Frontend unit-test runner (Vitest) 
  frontend-test:
    image: node:20-alpine
    working_dir: /usr/src/app
    environment:
      - CI=1
      - VITE_API_BASE=http://host.docker.internal:8089
      - npm_config_fund=false
      - npm_config_audit=false
    volumes:
      - ./frontend:/usr/src/app
      - node_modules_cache:/usr/src/app/node_modules
    command: >
      sh -lc '
        set -e
        LOCK=package-lock.json
        CACHE_DIR=node_modules
        HASH_FILE="$$CACHE_DIR/.lockhash"
        TEST_BIN="$$CACHE_DIR/.bin/vitest"

        if [ ! -x "$$TEST_BIN" ] || [ ! -f "$$HASH_FILE" ] || ! sha256sum -c "$$HASH_FILE" >/dev/null 2>&1; then
          echo "Installing dependencies (cache miss or lock changed)..."
          if [ -f "$$LOCK" ]; then
            npm ci --no-audit --no-fund
            sha256sum "$$LOCK" > "$$HASH_FILE"
          else
            npm install --no-audit --no-fund
          fi
        else
          echo "Using cached node_modules"
        fi

        exec npm run test
      '