version: "3.9"

volumes:
  vendor_cache: {}
  composer_cache: {}

services:
  test_db:
    image: mysql:8.0
    container_name: engineer_test_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${DB_ADMIN_PASSWORD} || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 40

  # Responsible solely for executing `composer install` and writing the vendor directory to the named volume; manually run once when composer.json/lock changes.
  deps:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    image: local/asknicely-test:8.2
    container_name: engineer_deps
    working_dir: /app
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    volumes:
      - ./backend:/app
      - vendor_cache:/app/vendor
      - composer_cache:/tmp/composer-cache
    command: >
      bash -lc '
        set -euo pipefail;
        composer install --no-interaction --prefer-dist
      '

  phpunit:
    image: local/asknicely-test:8.2
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: engineer_phpunit
    working_dir: /app
    depends_on:
      test_db:
        condition: service_healthy
      deps:
        condition: service_started
    env_file:
      - .env
    environment:
      DB_HOST: test_db
      DB_PORT: "3306"
      DB_NAME: asknicely_test
      DB_USER: asknicely_user
      DB_PASSWORD: asknicely_password
      DB_PASS: asknicely_password
    volumes:
      - ./backend:/app
      - vendor_cache:/app/vendor
    command: >
      bash -lc '
        set -euo pipefail;
        ./vendor/bin/phpunit --configuration phpunit.xml
      '
